### ISSUE TITLE
[docs] Project basic setting 

### ISSUE THREAD

**Issue by psh4607** [psh4607/blog#1]
# Todo List
- [x] prettier settings
    - [x] prettierrc, ignore
- [x] eslint settings
    - [x] alias 7659019eeb0cf8652d279d0f868a1f371f4afe7d
    - [x] lint error in boilerplates 9f9deb30c5e57c3d0048f176bcc732edd067b5bf
    - [x] eslintrc 
    - [x] rules
        - [x] no console.log with production env
- [ ] husky settings
    - [ ] pre-commit
- [x] babel settings
    - [x] add babelrc 4ad8e353a9d547ce7be345de9317e0320fe1f351
    - [x] styled-components de-hashing https://github.com/psh4607/blog/pull/4/commits/bf556c88ee337e5fea7934f6e7533e3c2145af45
- [x] webpack settings
    - [x] ts-loader 27f67342f298999183a83865745d1d8f84d17ec5
    - [x] babel-loader 671f5d47811430c3281191c7f8f89ee3cfe8f5fd
    - [x] alias 7659019eeb0cf8652d279d0f868a1f371f4afe7d
    - [x] config with env (dev or prod)
    - [x] modularization webpack (with helper method) 27f67342f298999183a83865745d1d8f84d17ec5
