### ISSUE TITLE
[Feature] Mac Style UX

### ISSUE THREAD

**Issue by psh4607** [psh4607/blog#2]
# Todo List
### Window UX
- [ ] Maximize window when click green button in header
- [x] #3
- [ ] Changed so that other windows can be moved freely like the vscode window
- [x] #6

### Bugs
- [ ] When refreshing, the current screen cannot be found.

### Contents
- [x] #10
- [x] #5
